## Aduxx Nagroda discord config
discord:
  Token: "Your token here" # Token bota discord
  channel-id: "1389174031315505183" # ID kanalu na ktorym ma zostać odebrana nagroda
  bot-activity: "Twojserwer.pl"
  activity-type: "PLAYING"  # Dostępne: WATCHING, COMPETING, PLAYING


reward-success:
  title: "** Udało się! **"
  description: "[DISCORD_PING_NICK] > Pomyślnie odebrałeś nagrodę na nick [PLAYER]!"
  embed-color: "#90EE90"
  embed-thumbnail-url: "https://i.postimg.cc/4x31q7TC/gg.png"

player-not-online:
  title: "** Błąd! **"
  description: "[DISCORD_PING_NICK] > Musisz być online na serwerze!"
  embed-color: "#FF6347"
  embed-thumbnail-url: "https://imgur.com/4uJWUSR.png"

player-not-found:
  title: "** Błąd! **"
  description: "[DISCORD_PING_NICK] > Ten nick jest niepoprawny!"
  embed-color: "#FF6347"
  embed-thumbnail-url: "https://imgur.com/4uJWUSR.png"

reward-picked:
  title: "** Błąd! **"
  description: "[DISCORD_PING_NICK] > Odebrałeś już swoją nagrodę!"
  embed-color: "#FF6347"
  embed-thumbnail-url: "https://imgur.com/4uJWUSR.png"


messages:
  reward-info: "&cMusisz najpierw &6powiązać &cswoje konto z naszym &6discordem!"
  reward-picked: "&cOdebrałeś już nagrodę!"
  picked-info: "&8>> &7Gracz &6[PLAYER] &7odebrał nagrodę za dołączenie do discorda &8>> &7Chcesz też? &7Sprawdź &e/nagroda"


reward-command: "give [PLAYER] diamond 5" #nagroda,która zostaje przyznana graczowi


gui:
  size: 45
  name: "&6&lNagroda discord"
  slots:
    0:  { item: YELLOW_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    1:  { item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    2:  { item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    3:  { item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    4:  { item: empty, name: " ", lore: [" "] }
    5:  { item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    6:  { item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    7:  { item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    8:  { item: YELLOW_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    9:  { item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    10: { item: empty, name: " ", lore: [" "] }
    11: { item: empty, name: " ", lore: [" "] }
    12: { item: empty, name: " ", lore: [" "] }
    13: { item: empty, name: " ", lore: [" "] }
    14: { item: empty, name: " ", lore: [" "] }
    15: { item: empty, name: " ", lore: [" "] }
    16: { item: empty, name: " ", lore: [" "] }
    17: { item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    18: { item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    19: { item: empty, name: " ", lore: [" "] }
    20: { item: empty, name: " ", lore: [" "] }
    21:
      item: PLAYER_HEAD

      name: "&x&0&0&5&7&9&D&lS&x&1&4&6&4&A&5&le&x&2&7&7&1&A&C&lr&x&3&B&7&E&B&4&lw&x&4&E&8&B&B&B&le&x&6&2&9&8&C&3&lr &x&8&9&B&1&D&2&ld&x&9&D&B&E&D&9&li&x&B&1&C&B&E&1&ls&x&C&4&D&8&E&8&lc&x&D&8&E&5&F&0&lo&x&E&B&F&2&F&7&lr&x&F&F&F&F&F&F&ld"
      lore:
        - " &8>> &7Połączono:&a✓ &c☓"
        - "&cJeśli chcesz odebrać nagrodę"
        - "&cmusisz połączyć swoje konto z Discordem."
        - "&cPod komendą &4/dc &cznajdziesz instrukcję."
        - ""
        - "&8>> &7Nagrody:"
        - " &8- &6Klucz do skrzyni &5&lStarbox"
        - ""
        - "&eKliknij, aby odebrać nagrodę!"
    22: { item: empty, name: " ", lore: [" "] }
    23: { item: empty, name: " ", lore: [" "] }
    24: { item: empty, name: " ", lore: [" "] }
    25: { item: empty, name: " ", lore: [" "] }
    26: { item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    27: { item: YELLOW_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    28: { item: empty, name: " ", lore: [" "] }
    29: { item: empty, name: " ", lore: [" "] }
    30: { item: empty, name: " ", lore: [" "] }
    31: { item: empty, name: " ", lore: [" "] }
    32: { item: empty, name: " ", lore: [" "] }
    33: { item: empty, name: " ", lore: [" "] }
    34: { item: empty, name: " ", lore: [" "] }
    35: { item: YELLOW_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    36: { item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    37: { item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    38: { item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    39: { item: empty, name: " ", lore: [" "] }
    40: { item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    41: { item: WHITE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    42: { item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "] }
    43: { item: ORANGE_STAINED_GLASS_PANE, name: " ", lore: [" "] }

